name: Test scheduler

on:
  schedule:
    - cron: "12 9 * * *"
      timezone: "Europe/Madrid"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger
        run: |
          echo "Triggered!"
          date -u
          echo "Event: ${{ github.event_name }}"
